name: Docker Build and Compose

on:
  push:
    branches:
      - main

jobs:
  build_and_compose:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        docker build -t myimage:latest -f Dockerfile . 

    - name: Run Docker Compose
      run: |
        docker-compose up -d 
        echo "app deployed"
        curl localhost:5003
