name: Docker Build and Compose

on:
  push:
    branches:
    - main

jobs:
  build_and_compose:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t myimage .
    - name: Start Docker services
      run: |
        docker-compose up -d
        echo "app deployed"
        curl localhost:5003
